name: app_flutter
description: A new Flutter project.

# Versão mínima do Flutter SDK necessário para rodar o projeto.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  http: ^0.13.6  # Fique com a versão 0.13.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
  leak_tracker: 10.0.5  # Fixar versão que é compatível com o flutter_test
  leak_tracker_flutter_testing: 3.0.5  # Fixar versão para evitar conflitos
